Repository PI1-UnB-Gama/web-server, pull requests merged in 2024-07, with the labels that each got.

#2 [build] Use `poetry` as the project dependency manager
  LICENSE
  README.md
  poetry.lock
  pyproject.toml
Labels: build, review needed

#4 [bug fix] Fix receive-data endpoint
  sensor/views.py
Labels: bug, review needed

#6 [chore] Add initial pre-commit hooks
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: chore
